development:
  adapter: postgresql
  database: mini_aircall
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>